#!/usr/bin/expect
########################################################################
# File Name: syncXavierClock.exp
# Use:./syncXavierClock.exp
########################################################################

set timeout 5

set setDate [exec date "+%Y-%m-%d %H:%M:%S"]

spawn ssh root@169.254.1.32 date -s \"$setDate\"

expect {
"*yes/no*"        { send "yes\n";exp_continue }
"*password*"    { send "123456\n" }
}

sleep 0.5

send sync

interact

sleep 0.5
